# Generated by Django 5.1.7 on 2025-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
