# Generated by Django 5.1.7 on 2025-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
