# Generated by Django 5.1.7 on 2025-03-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serg', '0002_alter_post_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
